[package]
name = "ytdl"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]

[dependencies]
clap = "2.25.0"
log = "0.3.8"
env_logger = "0.4.*"
url = "1.5.1"
reqwest = "0.7.0"
lazy_static = "0.2.8"
serde_derive = "1.0.10"
serde = "1.0.10"
serde_json = "1.0.2"
